spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/expense_tracker?useSSL=false
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      password: user
      name: user
